import type { Agent } from "./types";

/** 前端内置评审团数据，API 不可用时用于展示 */
export const STATIC_AGENTS: Agent[] = [
  {
    id: "agent_01",
    name: "张建国",
    role: "企业董事长",
    age: 58,
    background: "制造业集团创始人，三十年把公司做到年营收超50亿。",
    avatar: "/avatars/agent_01_zhang_jianguo.png",
    color: "#C9A84C",
    quote: "值不值得全公司学？",
    concerns: ["企业战略", "组织升级", "长期价值", "企业经营"],
  },
  {
    id: "agent_02",
    name: "李明辉",
    role: "总经理",
    age: 45,
    background: "从销售副总做起，管公司日常经营已有12年。",
    avatar: "/avatars/agent_02_li_minghui.png",
    color: "#4A7CFF",
    quote: "这个能不能落地？",
    concerns: ["经营", "组织管理", "团队执行", "流程优化"],
  },
  {
    id: "agent_03",
    name: "陈雅婷",
    role: "HRD",
    age: 42,
    background: "人力资源总监，亲手搭建了整个培训体系和干部培养机制。",
    avatar: "/avatars/agent_03_chen_yating.png",
    color: "#E8A0BF",
    quote: "不同层级感受会不一样",
    concerns: ["人才培养", "企业文化", "组织学习", "干部成长"],
  },
  {
    id: "agent_04",
    name: "王磊",
    role: "销售总监",
    age: 38,
    background: "制造业销售总监，管理30人销售团队，从业15年。",
    avatar: "/avatars/agent_04_wang_lei.png",
    color: "#F5A623",
    quote: "客户才不会管你这个",
    concerns: ["客户", "业绩", "业务", "竞争"],
  },
  {
    id: "agent_05",
    name: "赵卫东",
    role: "中层管理者",
    age: 40,
    background: "生产部门经理，管着120人的车间和3条生产线。",
    avatar: "/avatars/agent_05_zhao_weidong.png",
    color: "#2DD4BF",
    quote: "这个对我有用/没用",
    concerns: ["跨部门协作", "团队管理", "工作压力", "上下沟通"],
  },
  {
    id: "agent_06",
    name: "刘芳",
    role: "基层员工",
    age: 35,
    background: "公司行政部文员，入职8年，是普通共学课代表。",
    avatar: "/avatars/agent_06_liu_fang.png",
    color: "#D4A574",
    quote: "这跟我有什么关系？",
    concerns: ["真实感", "能不能听得懂", "有没有距离感"],
  },
  {
    id: "agent_07",
    name: "林晓雨",
    role: "95后年轻员工",
    age: 26,
    background: "入职两年的互联网运营，负责公司新媒体账号。",
    avatar: "/avatars/agent_07_lin_xiaoyu.png",
    color: "#A78BFA",
    quote: "愿不愿继续听？",
    concerns: ["表达是否有趣", "故事和情绪", "共鸣感"],
  },
  {
    id: "agent_08",
    name: "周文彬",
    role: "企业教练",
    age: 48,
    background: "外部签约企业教练，服务过30+家企业。",
    avatar: "/avatars/agent_08_zhou_wenbin.png",
    color: "#6EE7B7",
    quote: "这个点值得深挖",
    concerns: ["组织成长", "领导力", "共学效果"],
  },
  {
    id: "agent_09",
    name: "孙明德",
    role: "经典导师",
    age: 55,
    background: "国学与管理经典研究学者，出版过《论语与现代管理》。",
    avatar: "/avatars/agent_09_sun_mingde.png",
    color: "#C45C6E",
    quote: "此处恐有曲解",
    concerns: ["经典原意", "文化底蕴", "是否断章取义"],
  },
  {
    id: "agent_10",
    name: "何清源",
    role: "AI时代专家",
    age: 44,
    background: "科技战略顾问，专注AI时代的组织变革研究。",
    avatar: "/avatars/agent_10_he_qingyuan.png",
    color: "#38BDF8",
    quote: "经典回答了今天的问题吗？",
    concerns: ["现代价值", "AI时代关联", "时代连接"],
  },
];
